
###
# deepseek
POST https://api.deepseek.com/chat/completions
Authorization: Bearer {{DEEPSEEK_API_KEY}}
Content-Type: application/json

{
  "model": "deepseek-reasoner",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Hello!"
    }
  ],
  "stream": true
}

###