# https://goframe.org/docs/web/server-config-file-template
server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  path: "manifest/output/log"
  file: "{Y-m-d}.log"
  level : "all"
  stdout: true
  header: true

redis:
  address: "127.0.0.1:6379"
  password: ""

# https://goframe.org/docs/core/gdb-config-file
database:
  logger:
    path: "manifest/output/sql"
    level: "all"
    stdout: true
  default:
    link: "pgsql:spark-oj:123456@tcp(zrzring.top:54321)/spark-oj"
    timezone: "Asia/Shanghai"
    debug: true

thirdParty:
  codeforces:
    user:
      baseUrl: "https://codeforces.com/api/user.info"
      timeout: 15
  judge:
    baseUrl: "http://localhost:5050"
    timeout: 15