services:
  postgres:
    image: postgres:18.3
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spark-oj
      TZ: Asia/Shanghai
    command: ["postgres", "-c", "hba_file=/etc/postgresql/pg_hba.conf", "-c", "listen_addresses=*", "-c", "timezone=Asia/Shanghai"]
    volumes:
      - ./data/postgres:/var/lib/postgresql
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
  redis:
    image: redis:8.6.1
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  go-judge:
    image: registry.cn-hangzhou.aliyuncs.com/zrzring/go-judge
    container_name: go-judge
    restart: unless-stopped
    privileged: true
    shm_size: '256mb'
    ports:
      - "5050:5050"
      # - "5051:5051" # 如果需要开启 gRPC 接口，可以取消注释此端口并配置 ES_ENABLE_GRPC=true
      # - "5052:5052" # 如果需要开启 Metrics/Debug 监控，可以取消注释此端口并配置 ES_ENABLE_METRICS=true
    environment:
      # 更改文件存储路径（不在内存中运行则取消注释）
      # - ES_DIR=/opt/data
      # 允许复制进沙箱的本地源文件目录前缀
      - ES_SRC_PREFIX=/testcases
      # 开启 Prometheus 监控接口 (默认不开启)
      # - ES_ENABLE_METRICS=true
      # 设定接口鉴权 Token
      # - ES_AUTH_TOKEN=your_secret_key
    volumes:
      # 持久化文件存储，配合 ES_DIR=/opt/data 使用，将运行时的产物持久化到宿主机的 ./data 目录
      # - ./data/go-judge:/opt/data
      # 映射测试用例目录，配合 ES_SRC_PREFIX=/testcases 使用，通过相对路径向沙箱提供判题数据
      - ./data/testcases:/testcases:ro
      # Cgroup 映射，确保容器能正常管理沙箱进程的资源上限
      # - ./data/cgroup:/sys/fs/cgroup:rw
      # 自定义沙箱文件挂载配置，以高度定制沙箱内的文件系统视图
      - ./config/mount.yaml:/opt/mount.yaml:ro
      # 自定义 Seccomp 规则，用于限制恶意代码的系统调用
      - ./config/seccomp.yaml:/opt/seccomp.yaml:ro
    stdin_open: true
    tty: true