// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package submission

import (
	"spark-oj-server/api/submission"
)

type ControllerV1 struct{}

func NewV1() submission.ISubmissionV1 {
	return &ControllerV1{}
}
