// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package v1

import (
	"spark-oj-server/api/v1"
)

type ControllerUser struct{}

func NewUser() v1.IV1User {
	return &ControllerUser{}
}

type ControllerFile struct{}

func NewFile() v1.IV1File {
	return &ControllerFile{}
}

type ControllerAdmin struct{}

func NewAdmin() v1.IV1Admin {
	return &ControllerAdmin{}
}

type ControllerContest struct{}

func NewContest() v1.IV1Contest {
	return &ControllerContest{}
}

type ControllerProblem struct{}

func NewProblem() v1.IV1Problem {
	return &ControllerProblem{}
}

type ControllerSubmission struct{}

func NewSubmission() v1.IV1Submission {
	return &ControllerSubmission{}
}
