// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package contest

import (
	"spoj/api/contest"
)

type ControllerV1 struct{}

func NewV1() contest.IContestV1 {
	return &ControllerV1{}
}
