// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"spark-oj-server/internal/dao/internal"
)

// contestProblemDao is the data access object for the table contest_problem.
// You can define custom methods on it to extend its functionality as needed.
type contestProblemDao struct {
	*internal.ContestProblemDao
}

var (
	// ContestProblem is a globally accessible object for table contest_problem operations.
	ContestProblem = contestProblemDao{internal.NewContestProblemDao()}
)

// Add your custom methods and functionality below.
