// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"spoj/internal/dao/internal"
)

// contestDao is the data access object for the table contest.
// You can define custom methods on it to extend its functionality as needed.
type contestDao struct {
	*internal.ContestDao
}

var (
	// Contest is a globally accessible object for table contest operations.
	Contest = contestDao{internal.NewContestDao()}
)

// Add your custom methods and functionality below.
