// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"spark-oj-server/internal/dao/internal"
)

// problemContentDao is the data access object for the table problem_content.
// You can define custom methods on it to extend its functionality as needed.
type problemContentDao struct {
	*internal.ProblemContentDao
}

var (
	// ProblemContent is a globally accessible object for table problem_content operations.
	ProblemContent = problemContentDao{internal.NewProblemContentDao()}
)

// Add your custom methods and functionality below.
