// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"spoj/internal/dao/internal"
)

// problemDao is the data access object for the table problem.
// You can define custom methods on it to extend its functionality as needed.
type problemDao struct {
	*internal.ProblemDao
}

var (
	// Problem is a globally accessible object for table problem operations.
	Problem = problemDao{internal.NewProblemDao()}
)

// Add your custom methods and functionality below.
