// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"spoj/internal/dao/internal"
)

// submissionDao is the data access object for the table submission.
// You can define custom methods on it to extend its functionality as needed.
type submissionDao struct {
	*internal.SubmissionDao
}

var (
	// Submission is a globally accessible object for table submission operations.
	Submission = submissionDao{internal.NewSubmissionDao()}
)

// Add your custom methods and functionality below.
